package com.example.demo.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.demo.db.model.TbcInfo;

public interface TbcInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tbc_info
	 *
	 * @mbggenerated Wed Feb 07 20:33:49 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tbc_info
	 *
	 * @mbggenerated Wed Feb 07 20:33:49 CST 2018
	 */
	int insert(TbcInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tbc_info
	 *
	 * @mbggenerated Wed Feb 07 20:33:49 CST 2018
	 */
	int insertSelective(TbcInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tbc_info
	 *
	 * @mbggenerated Wed Feb 07 20:33:49 CST 2018
	 */
	TbcInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tbc_info
	 *
	 * @mbggenerated Wed Feb 07 20:33:49 CST 2018
	 */
	int updateByPrimaryKeySelective(TbcInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tbc_info
	 *
	 * @mbggenerated Wed Feb 07 20:33:49 CST 2018
	 */
	int updateByPrimaryKey(TbcInfo record);

	/**
	 * 查询所有预约信息
	 * 
	 * @return
	 */
	List<TbcInfo> selectAllMes();
	
	TbcInfo selectByTelphone(@Param("telphone")String telphone);
}