package com.springlight.data.db.model;

public class UnitBuild {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_build.unit_area
     *
     * @mbggenerated Mon Jan 08 12:31:50 CST 2018
     */
    private String unitArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_build.unit_build_name
     *
     * @mbggenerated Mon Jan 08 12:31:50 CST 2018
     */
    private String unitBuildName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit_build.unit_build_location
     *
     * @mbggenerated Mon Jan 08 12:31:50 CST 2018
     */
    private String unitBuildLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_build.unit_area
     *
     * @return the value of unit_build.unit_area
     *
     * @mbggenerated Mon Jan 08 12:31:50 CST 2018
     */
    public String getUnitArea() {
        return unitArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_build.unit_area
     *
     * @param unitArea the value for unit_build.unit_area
     *
     * @mbggenerated Mon Jan 08 12:31:50 CST 2018
     */
    public void setUnitArea(String unitArea) {
        this.unitArea = unitArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_build.unit_build_name
     *
     * @return the value of unit_build.unit_build_name
     *
     * @mbggenerated Mon Jan 08 12:31:50 CST 2018
     */
    public String getUnitBuildName() {
        return unitBuildName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_build.unit_build_name
     *
     * @param unitBuildName the value for unit_build.unit_build_name
     *
     * @mbggenerated Mon Jan 08 12:31:50 CST 2018
     */
    public void setUnitBuildName(String unitBuildName) {
        this.unitBuildName = unitBuildName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit_build.unit_build_location
     *
     * @return the value of unit_build.unit_build_location
     *
     * @mbggenerated Mon Jan 08 12:31:50 CST 2018
     */
    public String getUnitBuildLocation() {
        return unitBuildLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit_build.unit_build_location
     *
     * @param unitBuildLocation the value for unit_build.unit_build_location
     *
     * @mbggenerated Mon Jan 08 12:31:50 CST 2018
     */
    public void setUnitBuildLocation(String unitBuildLocation) {
        this.unitBuildLocation = unitBuildLocation;
    }
}