package com.springlight.data.db.model;

public class UnitRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_record.unit_sign
	 * @mbggenerated  Mon Jan 08 13:12:52 CST 2018
	 */
	private String unitSign;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_record.unit_read_num
	 * @mbggenerated  Mon Jan 08 13:12:52 CST 2018
	 */
	private Integer unitReadNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_record.unit_click_num
	 * @mbggenerated  Mon Jan 08 13:12:52 CST 2018
	 */
	private Integer unitClickNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_record.unit_click_build_num
	 * @mbggenerated  Mon Jan 08 13:12:52 CST 2018
	 */
	private Integer unitClickBuildNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_record.unit_sign
	 * @return  the value of unit_record.unit_sign
	 * @mbggenerated  Mon Jan 08 13:12:52 CST 2018
	 */
	public String getUnitSign() {
		return unitSign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_record.unit_sign
	 * @param unitSign  the value for unit_record.unit_sign
	 * @mbggenerated  Mon Jan 08 13:12:52 CST 2018
	 */
	public void setUnitSign(String unitSign) {
		this.unitSign = unitSign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_record.unit_read_num
	 * @return  the value of unit_record.unit_read_num
	 * @mbggenerated  Mon Jan 08 13:12:52 CST 2018
	 */
	public Integer getUnitReadNum() {
		return unitReadNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_record.unit_read_num
	 * @param unitReadNum  the value for unit_record.unit_read_num
	 * @mbggenerated  Mon Jan 08 13:12:52 CST 2018
	 */
	public void setUnitReadNum(Integer unitReadNum) {
		this.unitReadNum = unitReadNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_record.unit_click_num
	 * @return  the value of unit_record.unit_click_num
	 * @mbggenerated  Mon Jan 08 13:12:52 CST 2018
	 */
	public Integer getUnitClickNum() {
		return unitClickNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_record.unit_click_num
	 * @param unitClickNum  the value for unit_record.unit_click_num
	 * @mbggenerated  Mon Jan 08 13:12:52 CST 2018
	 */
	public void setUnitClickNum(Integer unitClickNum) {
		this.unitClickNum = unitClickNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_record.unit_click_build_num
	 * @return  the value of unit_record.unit_click_build_num
	 * @mbggenerated  Mon Jan 08 13:12:52 CST 2018
	 */
	public Integer getUnitClickBuildNum() {
		return unitClickBuildNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_record.unit_click_build_num
	 * @param unitClickBuildNum  the value for unit_record.unit_click_build_num
	 * @mbggenerated  Mon Jan 08 13:12:52 CST 2018
	 */
	public void setUnitClickBuildNum(Integer unitClickBuildNum) {
		this.unitClickBuildNum = unitClickBuildNum;
	}
}