package com.example.demo.db.model;

public class TbcBtnCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_btn_count.id
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_btn_count.btn_name
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    private String btnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_btn_count.btn_class
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    private String btnClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_btn_count.btn_num
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    private Integer btnNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_btn_count.btn_remark
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    private String btnRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_btn_count.id
     *
     * @return the value of tbc_btn_count.id
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_btn_count.id
     *
     * @param id the value for tbc_btn_count.id
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_btn_count.btn_name
     *
     * @return the value of tbc_btn_count.btn_name
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    public String getBtnName() {
        return btnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_btn_count.btn_name
     *
     * @param btnName the value for tbc_btn_count.btn_name
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    public void setBtnName(String btnName) {
        this.btnName = btnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_btn_count.btn_class
     *
     * @return the value of tbc_btn_count.btn_class
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    public String getBtnClass() {
        return btnClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_btn_count.btn_class
     *
     * @param btnClass the value for tbc_btn_count.btn_class
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    public void setBtnClass(String btnClass) {
        this.btnClass = btnClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_btn_count.btn_num
     *
     * @return the value of tbc_btn_count.btn_num
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    public Integer getBtnNum() {
        return btnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_btn_count.btn_num
     *
     * @param btnNum the value for tbc_btn_count.btn_num
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    public void setBtnNum(Integer btnNum) {
        this.btnNum = btnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_btn_count.btn_remark
     *
     * @return the value of tbc_btn_count.btn_remark
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    public String getBtnRemark() {
        return btnRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_btn_count.btn_remark
     *
     * @param btnRemark the value for tbc_btn_count.btn_remark
     *
     * @mbggenerated Wed Feb 07 21:17:26 CST 2018
     */
    public void setBtnRemark(String btnRemark) {
        this.btnRemark = btnRemark;
    }
}