package com.example.demo.db.model;

import java.util.Date;

public class TbcInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_info.id
     *
     * @mbggenerated Wed Feb 07 20:33:49 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_info.name
     *
     * @mbggenerated Wed Feb 07 20:33:49 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_info.telphone
     *
     * @mbggenerated Wed Feb 07 20:33:49 CST 2018
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_info.create_time
     *
     * @mbggenerated Wed Feb 07 20:33:49 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_info.id
     *
     * @return the value of tbc_info.id
     *
     * @mbggenerated Wed Feb 07 20:33:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_info.id
     *
     * @param id the value for tbc_info.id
     *
     * @mbggenerated Wed Feb 07 20:33:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_info.name
     *
     * @return the value of tbc_info.name
     *
     * @mbggenerated Wed Feb 07 20:33:49 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_info.name
     *
     * @param name the value for tbc_info.name
     *
     * @mbggenerated Wed Feb 07 20:33:49 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_info.telphone
     *
     * @return the value of tbc_info.telphone
     *
     * @mbggenerated Wed Feb 07 20:33:49 CST 2018
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_info.telphone
     *
     * @param telphone the value for tbc_info.telphone
     *
     * @mbggenerated Wed Feb 07 20:33:49 CST 2018
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_info.create_time
     *
     * @return the value of tbc_info.create_time
     *
     * @mbggenerated Wed Feb 07 20:33:49 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_info.create_time
     *
     * @param createTime the value for tbc_info.create_time
     *
     * @mbggenerated Wed Feb 07 20:33:49 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}