package com.example.demo.db.model;

public class TbcTelphone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_telphone.id
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_telphone.telphone_num
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    private String telphoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_telphone.product
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    private String product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_telphone.type
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_telphone.cornet
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    private String cornet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_telphone.department
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbc_telphone.reason
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_telphone.id
     *
     * @return the value of tbc_telphone.id
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_telphone.id
     *
     * @param id the value for tbc_telphone.id
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_telphone.telphone_num
     *
     * @return the value of tbc_telphone.telphone_num
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public String getTelphoneNum() {
        return telphoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_telphone.telphone_num
     *
     * @param telphoneNum the value for tbc_telphone.telphone_num
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public void setTelphoneNum(String telphoneNum) {
        this.telphoneNum = telphoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_telphone.product
     *
     * @return the value of tbc_telphone.product
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_telphone.product
     *
     * @param product the value for tbc_telphone.product
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public void setProduct(String product) {
        this.product = product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_telphone.type
     *
     * @return the value of tbc_telphone.type
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_telphone.type
     *
     * @param type the value for tbc_telphone.type
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_telphone.cornet
     *
     * @return the value of tbc_telphone.cornet
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public String getCornet() {
        return cornet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_telphone.cornet
     *
     * @param cornet the value for tbc_telphone.cornet
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public void setCornet(String cornet) {
        this.cornet = cornet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_telphone.department
     *
     * @return the value of tbc_telphone.department
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_telphone.department
     *
     * @param department the value for tbc_telphone.department
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbc_telphone.reason
     *
     * @return the value of tbc_telphone.reason
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbc_telphone.reason
     *
     * @param reason the value for tbc_telphone.reason
     *
     * @mbggenerated Wed Feb 07 19:37:34 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason;
    }
}