package com.springlight.data.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.springlight.data.db.model.UnitConfig;

public interface UnitConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_config
     *
     * @mbggenerated Thu Jan 04 18:00:37 CST 2018
     */
    int deleteByPrimaryKey(String unitSign);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_config
     *
     * @mbggenerated Thu Jan 04 18:00:37 CST 2018
     */
    int insert(UnitConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_config
     *
     * @mbggenerated Thu Jan 04 18:00:37 CST 2018
     */
    int insertSelective(UnitConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_config
     *
     * @mbggenerated Thu Jan 04 18:00:37 CST 2018
     */
    UnitConfig selectByPrimaryKey(String unitSign);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_config
     *
     * @mbggenerated Thu Jan 04 18:00:37 CST 2018
     */
    int updateByPrimaryKeySelective(@Param("unitConfig") UnitConfig record, @Param("upUnitSign")String unitSign);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_config
     *
     * @mbggenerated Thu Jan 04 18:00:37 CST 2018
     */
    int updateByPrimaryKey(UnitConfig record);
    
    /**
     * 查询所有数据
     * @return
     */
    List<UnitConfig> selectUnitConfigLs();
    
    List<UnitConfig> selectReportLs();
}