package com.springlight.data.db.dao;

import com.springlight.data.db.model.UnitRecord;

public interface UnitRecordMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unit_record
	 * 
	 * @mbggenerated Mon Jan 08 13:12:52 CST 2018
	 */
	int deleteByPrimaryKey(String unitSign);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unit_record
	 * 
	 * @mbggenerated Mon Jan 08 13:12:52 CST 2018
	 */
	int insert(UnitRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unit_record
	 * 
	 * @mbggenerated Mon Jan 08 13:12:52 CST 2018
	 */
	int insertSelective(UnitRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unit_record
	 * 
	 * @mbggenerated Mon Jan 08 13:12:52 CST 2018
	 */
	UnitRecord selectByPrimaryKey(String unitSign);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unit_record
	 * 
	 * @mbggenerated Mon Jan 08 13:12:52 CST 2018
	 */
	int updateByPrimaryKeySelective(UnitRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unit_record
	 * 
	 * @mbggenerated Mon Jan 08 13:12:52 CST 2018
	 */
	int updateByPrimaryKey(UnitRecord record);

	/**
	 * 更新浏览量加1
	 * 
	 * @param unitReadNum
	 * @param unitSign
	 */
	void updateReadNumByPrimaryKey(String unitSign);

	/**
	 * 更新点击量加1
	 * 
	 * @param unitClickNum
	 * @param unitSign
	 */
	void updateClickNumByPrimaryKey(String unitSign);

	/**
	 * 更新查询按钮点击量加1
	 * 
	 * @param unitSign
	 */
	void updateBuildClickNumByPrimaryKey(String unitSign);
}